services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycake
      POSTGRES_USER: root
      POSTGRES_PASSWORD: yeuwQ5uyxfIdf02Zh7BE
    ports:
      - "5432:5432"
  minio:
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minionetwork
    volumes:
      - "minio_data:/data"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=keycake

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
